name = "cf-email"
main = "src/worker.js"
compatibility_date = "2024-01-21"

kv_namespaces = [
  { binding = "", id = "" }
]

[vars]
ALLOWED_ORIGINS = ["http://localhost:3000", "https://your-domain.com"]
API_KEY = ""